language: node_js
node_js:
  - "node"

script:
- npm run lint

before_deploy:
- npm run build;
deploy:
  provider: pages
  local_dir: public/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
